# SPDX-License-Identifier: CC0-1.0
# SPDX-FileCopyrightText: 2025 Fundament Software SPC <https://fundament.software>

# The SPDX specification requires this to be under CC0-1.0:
# <https://spdx.github.io/spdx-spec/v2.3/document-creation-information/#62-data-license-field>

version = 1
SPDX-PackageName = "Feather-UI"
SPDX-PackageSupplier = "Fundament Software <https://fundament.software>"
SPDX-PackageDownloadLocation = "https://github.com/Fundament-Software/feathergui"

# Generated lock files, which are uncopyrightable. See:
# * <https://web.archive.org/web/20250214112110/https://github.com/fsfe/reuse-tool/issues/390>
# * <https://web.archive.org/web/20250106193945/https://reuse.software/faq/#uncopyrightable>
[[annotations]]
path = [
	"**/Cargo.lock",
	"**/flake.lock",
]
precedence = "closest"
SPDX-FileCopyrightText = "NONE"
SPDX-License-Identifier = "0BSD"

# Config files that we can't comment in.
[[annotations]]
path = [
	".vscode/**/*.json",
]
precedence = "closest"
SPDX-FileCopyrightText = "2025 Fundament Software SPC <https://fundament.software>"
SPDX-License-Identifier = "Apache-2.0"

# Config files that we can't comment in.
[[annotations]]
path = [
	".git-blame-ignore-revs",
	".luarc.json",
]
precedence = "closest"
SPDX-FileCopyrightText = "2025 Fundament Software SPC <https://fundament.software>"
SPDX-License-Identifier = "0BSD"

# Source/data files that we can't comment in.
[[annotations]]
path = [
	"testlist.json",
]
precedence = "closest"
SPDX-FileCopyrightText = "2025 Fundament Software SPC <https://fundament.software>"
SPDX-License-Identifier = "Apache-2.0"

# Source/data files that we don't want to comment in.
[[annotations]]
path = [
	"tests/*.alc",
]
precedence = "closest"
SPDX-FileCopyrightText = "2025 Fundament Software SPC <https://fundament.software>"
SPDX-License-Identifier = "Apache-2.0"

# Generated source/data files that we don't want to comment in.
[[annotations]]
path = [
	"types/*.lua",
]
precedence = "closest"
SPDX-FileCopyrightText = "2025 Fundament Software SPC <https://fundament.software>"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "vendor/lpeg/**"
precedence = "closest"
SPDX-FileCopyrightText = "Copyright © 2007-2023 Lua.org, PUC-Rio."
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "vendor/luafilesystem/**"
precedence = "closest"
SPDX-FileCopyrightText = "Copyright © 2010-2022 The LuaFileSystem authors. Copyright © 2003-2010 Kepler Project."
SPDX-License-Identifier = "MIT"
